#!/usr/bin/env lua
-- 新しいマシンでの初回セットアップは README 参照（SbarLua と lua 本体のビルドが必要）

package.cpath = package.cpath .. ";/Users/" .. os.getenv("USER") .. "/.local/share/sketchybar_lua/?.so"

sbar = require("sketchybar")

sbar.begin_config()
require("init")
sbar.hotload(true)
sbar.end_config()

sbar.event_loop()
